# Curso de instroducción a python
## Estructuras básicas

### Uso de variables, asignación, entrada  salida

In [2]:
# reading a parameter using input() function
name = input("Ingresa tu nobre: ")

Ingresa tu nobre: Reload


In [3]:
# writing an output for console using print() function
print(f"Tu nombre es: {name}")

Tu nombre es: Reload


In [4]:
# to print into a single line, change the ending value of print() function
print('Tu nombre es: ', end='**')
print(name)

Tu nombre es: **Reload


In [8]:
# Ejercicio 1
  #Convertir de horas a segundos la cantidad ingresada por el usuario

hours = input('Ingresa las horas a convertir: ')
hours = float(hours)
seconds = hours * 3600
print(f'{hours} horas equivalen a {seconds} segundos')

Ingresa las horas a convertir: 6
6.0 horas equivalen a 21600.0 segundos


## LISTAS

In [3]:
#Se puede crear un arreglo desde el módulo array
import array as arr
# el parámetro 'i' especifica el tipo entero para 
# los elementos del arreglo arr_ages
arr_ages = arr.array('i', [33, 26, 22, 28, 46, 19])
print(type(arr_ages))

<class 'array.array'>


Un array es mutable (variable).
Los elementos no necesariamente tienen que ser únicos.
Las operaciones más comunes en los arreglos: 

- *Indexing*
- *Slicing*
- *Iterating*

In [4]:
# Utilizando el módulo numpy para crear el arreglo
import numpy as np
arr_ages2 = np.array(["S/N", 33, 26, 19, 42])
print(type(arr_ages2))
print(arr_ages2)

<class 'numpy.ndarray'>
['S/N' '33' '26' '19' '42']


In [5]:
list_numbers = [2, 3, 4, 5]
print(list_numbers)

[2, 3, 4, 5]


In [6]:
# Imprime el tamaño del arreglo
print(len(list_numbers))

4


In [14]:
# Ejercicio de listas
list_cars = ['Ford', 'Renault', 'Toyota']
list_bikes = ['Fox', 'Shimano', 'Trek']

# Concatenar listas
list_vehicles = list_cars + list_bikes
print(list_vehicles)

['Ford', 'Renault', 'Toyota', 'Fox', 'Shimano', 'Trek']


In [13]:
# Buscar elemento en la lista
if 'Alfa Romeo' in list_vehicles:
    print("Mi auto esta en la lista")
else:
    print("Busca otro auto")

Busca otro auto


In [19]:
# Multiplicando la lista, incrementa los elementos
# no influye en el valor de cada elemento
list_items = [3, 5, 8]
list_store = list_items * 3
print(list_store)

[3, 5, 8, 3, 5, 8, 3, 5, 8]


In [20]:
# Slicing
list_fibo = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

# Comenzando la extracción con rangos
# Desde el inicio hasta el límite del índice 4
list_fibo[:4]

[1, 2, 3, 5]

In [21]:
# Del inicio del índice 5 hasta el final
list_fibo[5:]

[13, 21, 34, 55, 89]

In [23]:
# Del inicio del índice 2 hasta el inicio del índice 6
list_fibo[2:6]

[3, 5, 8, 13]

In [26]:
# Realizando saltos de dos elementos
list_fibo[2:6:2]

[3, 8]

In [28]:
# Tomando el último elemento
list_fibo[-1]

89

In [30]:
# Tomando desde el inicio al fin de la lista pero comenzando del último elemento
list_fibo[::-1]

[89, 55, 34, 21, 13, 8, 5, 3, 2, 1]

In [32]:
# Algunas funciones de listas
L1 = ['a', 'b', 'c']
L2 = ['d', 'e', 'f']
# Concatenando valores de listas con operador +
L1 + L2

['a', 'b', 'c', 'd', 'e', 'f']

In [33]:
# Agregando un elemento a la lista
L1.append(L2)
L1

['a', 'b', 'c', ['d', 'e', 'f']]

In [34]:
L1 = ['a', 'b', 'c']

# Se agregan los elementos a la lista 
L1.extend(L2)
L1

['a', 'b', 'c', 'd', 'e', 'f']

In [38]:
L1 = ['a', 'b', 'c']

# Se inserta un elemento en la posición solicitada como argumento
L1.insert(0, 'z')
L1

['z', 'a', 'b', 'c']

In [39]:
# Hacer copia de una lista con la función COPY
list_numbers = [1,2,3,4,5]
list_copy = list_numbers.copy()
list_copy

[1, 2, 3, 4, 5]

In [40]:
# Hacer copia de una lista con slicing y un rango
list_copy2 = list_numbers[::]
list_copy2

[1, 2, 3, 4, 5]

In [41]:
# Creando otra lista
list_names = ['Luis', 'Camila', 'Carlos', 'Jorge']
list_names

['Luis', 'Camila', 'Carlos', 'Jorge']

In [45]:
# Utilizando la función index para conocer la
# posición de un elemento en la lista
list_names.index('Camila')

1

In [46]:
# Convertir una cadena a lista
food = 'arroz'
type(food)

str

In [47]:
list(food)

['a', 'r', 'r', 'o', 'z']

In [48]:
len(food)

5

In [51]:
# Convirtiendo la cadena completa como un elemento de la lista
list([food, food, 'gundam'])

['arroz', 'arroz', 'gundam']

## Trabajando con arreglos

In [52]:
# Importando el paquete numpy
import numpy as np

In [53]:
# Creando un arreglo de 1 dimensión
arr_numbers_1D = np.array([1,2,3,4])
print(arr_numbers_1D)

[1 2 3 4]


In [55]:
# Creando una matriz
arr_numbers_2D = np.array([(1,2,3,4), (6,7,8,9)])
print(arr_numbers_2D)

[[1 2 3 4]
 [6 7 8 9]]


In [57]:
# Creando una lista de elementos del 0 al 10 utilizando la función range

# Creando rango
range_large = range(10)
print(type(range_large), range_large)

<class 'range'> range(0, 10)


In [58]:
# Convirtiendo rango a lista
list_large = list(range_large)
print(list_large)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [59]:
# Creando un numpy array de la lista
arr_large = np.array(list_large)

In [60]:
# Imprimiendo la lista y el numpy array
print(list_large), print(arr_large)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


(None, None)

In [61]:
# Tratando de concatenar con + una lista y un número
lst_large = list_large + 10

TypeError: can only concatenate list (not "int") to list

In [62]:
# Operador + sobre un numpy array
arr_large = arr_large + 10
arr_large

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Ordenando elementos
Es posible ordenar los elementos de una lista empleando la función `sort()` y `sorted()`. La primera lo ordena y modifica la lista en cuestión, la segunda devuelve o retoma la lista ordenada como una variable.

In [63]:
arr_names = ['Rafael', 'Omar', 'Edgar', 'Pat']
#SORTED no modifica el array original
print(sorted(arr_names))

['Edgar', 'Omar', 'Pat', 'Rafael']


In [64]:
#SORT modifica el array original
arr_names.sort()
arr_names

['Edgar', 'Omar', 'Pat', 'Rafael']

In [66]:
# Ordenando en forma descendente
arr_names.sort(reverse=True)
arr_names

['Rafael', 'Pat', 'Omar', 'Edgar']

In [67]:
# Uniendo los nombres en un string
str_names = ", ".join(arr_names)
print(f'Los nombres son: {str_names}')

Los nombres son: Rafael, Pat, Omar, Edgar


## Combinando elementos

In [1]:
# Listas iniciales que se desean combinar
list_numbers = [1,2,3,4]
list_names = ['Antonio', 'Sergio', 'Lewis', 'Esteban']

In [3]:
# Utilizando la función zip para combinar los elementos
list_combined = zip(list_numbers, list_names)
print(list_combined)

In [4]:
# convertir el objeto zip a un objeto lista
list_combined = list(list_combined)
print(list_combined)

[(1, 'Antonio'), (2, 'Sergio'), (3, 'Lewis'), (4, 'Esteban')]


## itertools
Está compuesto por funciones que crean código rápido, eficiente en memoria y de buen aspecto. Según la documentación, itertools permite construir bloques de iteradores

In [21]:
# Creando un objeto iterador
list_iter = range(1,6)
list(list_iter)

[1, 2, 3, 4, 5]

In [15]:
# Creando dos listas, 5 números y 5 letras
list_numbers = [1,2,3,4,5]
list_letters = ['a', 'b', 'c']

In [16]:
# Utilizando la función zip para combinarlas
list_combined = zip(list_numbers, list_letters)
print(list(list_combined))

[(1, 'a'), (2, 'b'), (3, 'c')]


In [17]:
# Importando el módulo itertools
import itertools as itt

In [18]:
# COmbinando las listas previamente definidas
list(itt.zip_longest(list_numbers, list_letters))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, None), (5, None)]

In [19]:
# None es un objeto complejo
type(None), print()

(NoneType, None)

In [22]:
# creando una lista a partir de un rango para permutarla
list_example = list(range(3))
list_example

[0, 1, 2]

In [23]:
list(itt.permutations(list_example))

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [24]:
# Imprimiendo listas que se permutarán
list_numbers, list_letters

([1, 2, 3, 4, 5], ['a', 'b', 'c'])

In [26]:
list_product = list(itt.product(list_numbers, list_letters))
list_product

[(1, 'a'),
 (1, 'b'),
 (1, 'c'),
 (2, 'a'),
 (2, 'b'),
 (2, 'c'),
 (3, 'a'),
 (3, 'b'),
 (3, 'c'),
 (4, 'a'),
 (4, 'b'),
 (4, 'c'),
 (5, 'a'),
 (5, 'b'),
 (5, 'c')]

## Ejercicio

### Criptografía con César
La criptografía es el arte y técnica de escribor con procedimientos o claves secretas o de un modo enigmático, de tal forma que lo escrito solamente sea inteligible para quien sepa descifrarlo. En este ámbito, existe una técnica llamada [Cifrado César](https://es.wikipedia.org/wiki/Cifrado_César), que consiste en reemplazar cada letra de un texto por otra letra que se encuentra un número fijo de posiciones más adelante o más atrás en el alfabeto.

**Entrada**
Para el algoritmo se dispone de dos variables `name` y `shift`. La variable `name` repersenta una lista que contiene 3 valores, cada valor representa a una letra del alfabeto, y `shift` representa a un valor entero (positivo o negativo) que representa el desplazamiento del alfabeto para el cifrado. Para esta prueba, se empleará el alfabéto que consta de 26 letras (A - Z) y siempre en mayúsculas

**Salida**
Se requiere imprimir el contenido de una lista con el valor cifrado.

In [9]:
#Alphabet variable to support to you! remenber: [65, 66, 67, ..., 90] de acuredo al código ASCII
alphabet = list(range(65, 91))
print (alphabet)

[65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


In [10]:
#name contains a list of 3 letters (e.g. ['A', 'B', 'C'])
name = ['A', 'B', 'C']
print (name)

['A', 'B', 'C']


In [15]:
#shift contains an integer number (positivo or negative in a range from -999 to 999)
shift = -26
print(shift)

-26


In [ ]:
name_coded = []
for letter in name:
    letter_coded = (ord(letter))
    index = alphabet.index(letter_coded) + shift
    if index < 0:
        index = index % 26 - 26
    else:
        index = index % 26
    name_coded.append(chr(alphabet[index]))
print (name_coded)

## Iteraciones

In [29]:
index = 0
while True:
    print(index)
    if index == 5:
        print('Llegando al 5')
    if index == 10:
        print('Llegamos al 10 y nos vamos')
        break
    index += 1
    

0
1
2
3
4
5
Llegando al 5
6
7
8
9
10
Llegamos al 10 y nos vamos
