# Curso de instroducción a python
## Estructuras básicas

### Uso de variables, asignación, entrada  salida

In [2]:
# reading a parameter using input() function
name = input("Ingresa tu nobre: ")

Ingresa tu nobre: Reload


In [3]:
# writing an output for console using print() function
print(f"Tu nombre es: {name}")

Tu nombre es: Reload


In [4]:
# to print into a single line, change the ending value of print() function
print('Tu nombre es: ', end='**')
print(name)

Tu nombre es: **Reload


In [8]:
# Ejercicio 1
  #Convertir de horas a segundos la cantidad ingresada por el usuario

hours = input('Ingresa las horas a convertir: ')
hours = float(hours)
seconds = hours * 3600
print(f'{hours} horas equivalen a {seconds} segundos')

Ingresa las horas a convertir: 6
6.0 horas equivalen a 21600.0 segundos


## LISTAS

In [3]:
#Se puede crear un arreglo desde el módulo array
import array as arr
# el parámetro 'i' especifica el tipo entero para 
# los elementos del arreglo arr_ages
arr_ages = arr.array('i', [33, 26, 22, 28, 46, 19])
print(type(arr_ages))

<class 'array.array'>


Un array es mutable (variable).
Los elementos no necesariamente tienen que ser únicos.
Las operaciones más comunes en los arreglos: 

- *Indexing*
- *Slicing*
- *Iterating*

In [4]:
# Utilizando el módulo numpy para crear el arreglo
import numpy as np
arr_ages2 = np.array(["S/N", 33, 26, 19, 42])
print(type(arr_ages2))
print(arr_ages2)

<class 'numpy.ndarray'>
['S/N' '33' '26' '19' '42']


In [5]:
list_numbers = [2, 3, 4, 5]
print(list_numbers)

[2, 3, 4, 5]


In [6]:
# Imprime el tamaño del arreglo
print(len(list_numbers))

4


In [14]:
# Ejercicio de listas
list_cars = ['Ford', 'Renault', 'Toyota']
list_bikes = ['Fox', 'Shimano', 'Trek']

# Concatenar listas
list_vehicles = list_cars + list_bikes
print(list_vehicles)

['Ford', 'Renault', 'Toyota', 'Fox', 'Shimano', 'Trek']


In [13]:
# Buscar elemento en la lista
if 'Alfa Romeo' in list_vehicles:
    print("Mi auto esta en la lista")
else:
    print("Busca otro auto")

Busca otro auto


In [19]:
# Multiplicando la lista, incrementa los elementos
# no influye en el valor de cada elemento
list_items = [3, 5, 8]
list_store = list_items * 3
print(list_store)

[3, 5, 8, 3, 5, 8, 3, 5, 8]


In [20]:
# Slicing
list_fibo = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

# Comenzando la extracción con rangos
# Desde el inicio hasta el límite del índice 4
list_fibo[:4]

[1, 2, 3, 5]

In [21]:
# Del inicio del índice 5 hasta el final
list_fibo[5:]

[13, 21, 34, 55, 89]

In [23]:
# Del inicio del índice 2 hasta el inicio del índice 6
list_fibo[2:6]

[3, 5, 8, 13]

In [26]:
# Realizando saltos de dos elementos
list_fibo[2:6:2]

[3, 8]

In [28]:
# Tomando el último elemento
list_fibo[-1]

89

In [30]:
# Tomando desde el inicio al fin de la lista pero comenzando del último elemento
list_fibo[::-1]

[89, 55, 34, 21, 13, 8, 5, 3, 2, 1]

In [32]:
# Algunas funciones de listas
L1 = ['a', 'b', 'c']
L2 = ['d', 'e', 'f']
# Concatenando valores de listas con operador +
L1 + L2

['a', 'b', 'c', 'd', 'e', 'f']

In [33]:
# Agregando un elemento a la lista
L1.append(L2)
L1

['a', 'b', 'c', ['d', 'e', 'f']]

In [34]:
L1 = ['a', 'b', 'c']

# Se agregan los elementos a la lista 
L1.extend(L2)
L1

['a', 'b', 'c', 'd', 'e', 'f']

In [38]:
L1 = ['a', 'b', 'c']

# Se inserta un elemento en la posición solicitada como argumento
L1.insert(0, 'z')
L1

['z', 'a', 'b', 'c']

In [39]:
# Hacer copia de una lista con la función COPY
list_numbers = [1,2,3,4,5]
list_copy = list_numbers.copy()
list_copy

[1, 2, 3, 4, 5]

In [40]:
# Hacer copia de una lista con slicing y un rango
list_copy2 = list_numbers[::]
list_copy2

[1, 2, 3, 4, 5]

In [41]:
# Creando otra lista
list_names = ['Luis', 'Camila', 'Carlos', 'Jorge']
list_names

['Luis', 'Camila', 'Carlos', 'Jorge']

In [45]:
# Utilizando la función index para conocer la
# posición de un elemento en la lista
list_names.index('Camila')

1

In [46]:
# Convertir una cadena a lista
food = 'arroz'
type(food)

str

In [47]:
list(food)

['a', 'r', 'r', 'o', 'z']

In [48]:
len(food)

5

In [51]:
# Convirtiendo la cadena completa como un elemento de la lista
list([food, food, 'gundam'])

['arroz', 'arroz', 'gundam']

## Trabajando con arreglos

In [52]:
# Importando el paquete numpy
import numpy as np

In [53]:
# Creando un arreglo de 1 dimensión
arr_numbers_1D = np.array([1,2,3,4])
print(arr_numbers_1D)

[1 2 3 4]


In [55]:
# Creando una matriz
arr_numbers_2D = np.array([(1,2,3,4), (6,7,8,9)])
print(arr_numbers_2D)

[[1 2 3 4]
 [6 7 8 9]]


In [57]:
# Creando una lista de elementos del 0 al 10 utilizando la función range

# Creando rango
range_large = range(10)
print(type(range_large), range_large)

<class 'range'> range(0, 10)


In [58]:
# Convirtiendo rango a lista
list_large = list(range_large)
print(list_large)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [59]:
# Creando un numpy array de la lista
arr_large = np.array(list_large)

In [60]:
# Imprimiendo la lista y el numpy array
print(list_large), print(arr_large)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


(None, None)

In [61]:
# Tratando de concatenar con + una lista y un número
lst_large = list_large + 10

TypeError: can only concatenate list (not "int") to list

In [62]:
# Operador + sobre un numpy array
arr_large = arr_large + 10
arr_large

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Ordenando elementos
Es posible ordenar los elementos de una lista empleando la función `sort()` y `sorted()`. La primera lo ordena y modifica la lista en cuestión, la segunda devuelve o retoma la lista ordenada como una variable.

In [63]:
arr_names = ['Rafael', 'Omar', 'Edgar', 'Pat']
#SORTED no modifica el array original
print(sorted(arr_names))

['Edgar', 'Omar', 'Pat', 'Rafael']


In [64]:
#SORT modifica el array original
arr_names.sort()
arr_names

['Edgar', 'Omar', 'Pat', 'Rafael']

In [66]:
# Ordenando en forma descendente
arr_names.sort(reverse=True)
arr_names

['Rafael', 'Pat', 'Omar', 'Edgar']

In [67]:
# Uniendo los nombres en un string
str_names = ", ".join(arr_names)
print(f'Los nombres son: {str_names}')

Los nombres son: Rafael, Pat, Omar, Edgar


## Combinando elementos

In [1]:
# Listas iniciales que se desean combinar
list_numbers = [1,2,3,4]
list_names = ['Antonio', 'Sergio', 'Lewis', 'Esteban']

In [3]:
# Utilizando la función zip para combinar los elementos
list_combined = zip(list_numbers, list_names)
print(list_combined)

In [4]:
# convertir el objeto zip a un objeto lista
list_combined = list(list_combined)
print(list_combined)

[(1, 'Antonio'), (2, 'Sergio'), (3, 'Lewis'), (4, 'Esteban')]


## itertools
Está compuesto por funciones que crean código rápido, eficiente en memoria y de buen aspecto. Según la documentación, itertools permite construir bloques de iteradores

In [21]:
# Creando un objeto iterador
list_iter = range(1,6)
list(list_iter)

[1, 2, 3, 4, 5]

In [15]:
# Creando dos listas, 5 números y 5 letras
list_numbers = [1,2,3,4,5]
list_letters = ['a', 'b', 'c']

In [16]:
# Utilizando la función zip para combinarlas
list_combined = zip(list_numbers, list_letters)
print(list(list_combined))

[(1, 'a'), (2, 'b'), (3, 'c')]


In [17]:
# Importando el módulo itertools
import itertools as itt

In [18]:
# COmbinando las listas previamente definidas
list(itt.zip_longest(list_numbers, list_letters))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, None), (5, None)]

In [19]:
# None es un objeto complejo
type(None), print()

(NoneType, None)

In [22]:
# creando una lista a partir de un rango para permutarla
list_example = list(range(3))
list_example

[0, 1, 2]

In [23]:
list(itt.permutations(list_example))

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [24]:
# Imprimiendo listas que se permutarán
list_numbers, list_letters

([1, 2, 3, 4, 5], ['a', 'b', 'c'])

In [26]:
list_product = list(itt.product(list_numbers, list_letters))
list_product

[(1, 'a'),
 (1, 'b'),
 (1, 'c'),
 (2, 'a'),
 (2, 'b'),
 (2, 'c'),
 (3, 'a'),
 (3, 'b'),
 (3, 'c'),
 (4, 'a'),
 (4, 'b'),
 (4, 'c'),
 (5, 'a'),
 (5, 'b'),
 (5, 'c')]

## Ejercicio

### Criptografía con César
La criptografía es el arte y técnica de escribor con procedimientos o claves secretas o de un modo enigmático, de tal forma que lo escrito solamente sea inteligible para quien sepa descifrarlo. En este ámbito, existe una técnica llamada [Cifrado César](https://es.wikipedia.org/wiki/Cifrado_César), que consiste en reemplazar cada letra de un texto por otra letra que se encuentra un número fijo de posiciones más adelante o más atrás en el alfabeto.

**Entrada**
Para el algoritmo se dispone de dos variables `name` y `shift`. La variable `name` repersenta una lista que contiene 3 valores, cada valor representa a una letra del alfabeto, y `shift` representa a un valor entero (positivo o negativo) que representa el desplazamiento del alfabeto para el cifrado. Para esta prueba, se empleará el alfabéto que consta de 26 letras (A - Z) y siempre en mayúsculas

**Salida**
Se requiere imprimir el contenido de una lista con el valor cifrado.

In [9]:
#Alphabet variable to support to you! remenber: [65, 66, 67, ..., 90] de acuredo al código ASCII
alphabet = list(range(65, 91))
print (alphabet)

[65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


In [10]:
#name contains a list of 3 letters (e.g. ['A', 'B', 'C'])
name = ['A', 'B', 'C']
print (name)

['A', 'B', 'C']


In [15]:
#shift contains an integer number (positivo or negative in a range from -999 to 999)
shift = -26
print(shift)

-26


In [ ]:
name_coded = []
for letter in name:
    letter_coded = (ord(letter))
    index = alphabet.index(letter_coded) + shift
    if index < 0:
        index = index % 26 - 26
    else:
        index = index % 26
    name_coded.append(chr(alphabet[index]))
print (name_coded)

## Iteraciones

In [29]:
index = 0
while True:
    print(index)
    if index == 5:
        print('Llegando al 5')
    if index == 10:
        print('Llegamos al 10 y nos vamos')
        break
    index += 1
    

0
1
2
3
4
5
Llegando al 5
6
7
8
9
10
Llegamos al 10 y nos vamos


In [2]:
#Más operaciones con while
list_names = ['Anna', 'Javier', 'Orianna', 'Malfoy', 'Ricciardo']
while list_names:
    print(list_names, end=' ->')
    list_names.pop()
    print(list_names)

['Anna', 'Javier', 'Orianna', 'Malfoy', 'Ricciardo'] ->['Anna', 'Javier', 'Orianna', 'Malfoy']
['Anna', 'Javier', 'Orianna', 'Malfoy'] ->['Anna', 'Javier', 'Orianna']
['Anna', 'Javier', 'Orianna'] ->['Anna', 'Javier']
['Anna', 'Javier'] ->['Anna']
['Anna'] ->[]


In [3]:
#while in one line
index = 0
while index < 5: index += 1; print(f'index: {index}')

index: 1
index: 2
index: 3
index: 4
index: 5


In [5]:
#print a multiplication table from 1 to 10
value_i = 1
value_j = 1

while value_i <= 10:
    while value_j <= 10:
        print(f'{value_i}x{value_j} = {value_i*value_j}')
        value_j += 1
    value_j = 1
    value_i += 1

1x1 = 1
1x2 = 2
1x3 = 3
1x4 = 4
1x5 = 5
1x6 = 6
1x7 = 7
1x8 = 8
1x9 = 9
1x10 = 10
2x1 = 2
2x2 = 4
2x3 = 6
2x4 = 8
2x5 = 10
2x6 = 12
2x7 = 14
2x8 = 16
2x9 = 18
2x10 = 20
3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
3x10 = 30
4x1 = 4
4x2 = 8
4x3 = 12
4x4 = 16
4x5 = 20
4x6 = 24
4x7 = 28
4x8 = 32
4x9 = 36
4x10 = 40
5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
5x10 = 50
6x1 = 6
6x2 = 12
6x3 = 18
6x4 = 24
6x5 = 30
6x6 = 36
6x7 = 42
6x8 = 48
6x9 = 54
6x10 = 60
7x1 = 7
7x2 = 14
7x3 = 21
7x4 = 28
7x5 = 35
7x6 = 42
7x7 = 49
7x8 = 56
7x9 = 63
7x10 = 70
8x1 = 8
8x2 = 16
8x3 = 24
8x4 = 32
8x5 = 40
8x6 = 48
8x7 = 56
8x8 = 64
8x9 = 72
8x10 = 80
9x1 = 9
9x2 = 18
9x3 = 27
9x4 = 36
9x5 = 45
9x6 = 54
9x7 = 63
9x8 = 72
9x9 = 81
9x10 = 90
10x1 = 10
10x2 = 20
10x3 = 30
10x4 = 40
10x5 = 50
10x6 = 60
10x7 = 70
10x8 = 80
10x9 = 90
10x10 = 100


Iterando con for sobre listas, rangos y errores comunes

In [6]:
# print all letters of a string
str_name = 'professional'
for letter in str_name:
    print(letter)

p
r
o
f
e
s
s
i
o
n
a
l


In [10]:
# print all items of a list
list_words = ['Remember', 'to', 'take', 'your', 'meds', 'at', '10am']
for word in list_words:
    print(word)

Remember
to
take
your
meds
at
10am


In [11]:
# print all letters of each word of a list
list_words = ['Remember', 'to', 'take', 'your', 'meds']
for word in list_words:
    for letter in word:
        print(letter)

R
e
m
e
m
b
e
r
t
o
t
a
k
e
y
o
u
r
m
e
d
s


In [12]:
# Print integer values from a list
for x in [1,2,3,4,5]:
    print(x)

1
2
3
4
5


In [14]:
# print all integers from a range object
for x in range(1,6):
    print(x)

1
2
3
4
5


In [16]:
# print all integers from a range object using a step of 2
for x in range(1, 12, 2):
    print(x)

1
3
5
7
9
11


**Interrumpiendo el cliclo usando break y continue**

In [18]:
#using break after a print
for x in range(0, 12, 2):
    print(x)
    if x == 4:
        break

0
2
4


In [19]:
#Using continue and printing the word if contains 's' letter 
list_words = ['This', 'is', 'a', 'test']
for word in list_words:
    if 's' in word:
        continue
    print(word)

a


**Range junto con for**

In [20]:
# create a for-range to print values in reverse
for index in range(10, 0, -1):
    print(index)

10
9
8
7
6
5
4
3
2
1


In [21]:
# adding values into a list using append
list_values = []

for value in range(20):
    list_values.append(pow(value, 3))

print(list_values)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859]


In [22]:
# copy values using a for from one list to another
list_number = [1, 2, 3, 4, 5]
list_result = []

for index in list_number:
    list_result.append(index)
print(list_result)

# list_result = list_number.copy() it's a better approach

[1, 2, 3, 4, 5]


**List comprehension**
Sirve para todo tipo de colecciones

In [23]:
# copy values from a list to another using list comprehension
list_result = []
list_result = [index for index in list_number]
print(list_result)

[1, 2, 3, 4, 5]


In [24]:
# list comrehension for a string 
name = 'Python'
[letter for letter in name]

['P', 'y', 't', 'h', 'o', 'n']

In [26]:
# get all even numbers from [0 to 40] and store them into a list with list comprehension
[number for number in range(40) if number % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [27]:
# usage of if/else in list comprehension
[f'{number} es par' if number % 2 == 0 else f'{number} es impar' for number in range(10)]

['0 es par',
 '1 es impar',
 '2 es par',
 '3 es impar',
 '4 es par',
 '5 es impar',
 '6 es par',
 '7 es impar',
 '8 es par',
 '9 es impar']

In [28]:
# using implicit return + if sentence in the comprehesion
list_numbers = [number**2 for number in range(0,40) if number % 2 == 0]
print(list_numbers)

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444]


In [29]:
# (power of 2) of multiples of 2 and 3 in a range (1 - 40)
[(number, pow(number, 2)) for number in range(1,40) if number % 2 == 0 if number % 3 == 0]

[(6, 36), (12, 144), (18, 324), (24, 576), (30, 900), (36, 1296)]

In [33]:
# tabla de multiplicacion usando doble comprension de listas
table = [print(f'{value_i}x{value_j} = {value_i*value_j}') for value_i in range(1,11) for value_j in range(1,11)]

1x1 = 1
1x2 = 2
1x3 = 3
1x4 = 4
1x5 = 5
1x6 = 6
1x7 = 7
1x8 = 8
1x9 = 9
1x10 = 10
2x1 = 2
2x2 = 4
2x3 = 6
2x4 = 8
2x5 = 10
2x6 = 12
2x7 = 14
2x8 = 16
2x9 = 18
2x10 = 20
3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
3x10 = 30
4x1 = 4
4x2 = 8
4x3 = 12
4x4 = 16
4x5 = 20
4x6 = 24
4x7 = 28
4x8 = 32
4x9 = 36
4x10 = 40
5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
5x10 = 50
6x1 = 6
6x2 = 12
6x3 = 18
6x4 = 24
6x5 = 30
6x6 = 36
6x7 = 42
6x8 = 48
6x9 = 54
6x10 = 60
7x1 = 7
7x2 = 14
7x3 = 21
7x4 = 28
7x5 = 35
7x6 = 42
7x7 = 49
7x8 = 56
7x9 = 63
7x10 = 70
8x1 = 8
8x2 = 16
8x3 = 24
8x4 = 32
8x5 = 40
8x6 = 48
8x7 = 56
8x8 = 64
8x9 = 72
8x10 = 80
9x1 = 9
9x2 = 18
9x3 = 27
9x4 = 36
9x5 = 45
9x6 = 54
9x7 = 63
9x8 = 72
9x9 = 81
9x10 = 90
10x1 = 10
10x2 = 20
10x3 = 30
10x4 = 40
10x5 = 50
10x6 = 60
10x7 = 70
10x8 = 80
10x9 = 90
10x10 = 100
